- hosts: localhost
  tasks:
    - name: Get system hostname
      command: "hostname"
      register: command_output
    - name: Set system hostname fact
      set_fact:
        system_hostname: "{{  command_output.stdout  }}"

- import_playbook: child1.yml
  when: system_hostname is defined
- import_playbook: child2.yml
  when: system_hostname is not defined
- import_playbook: child3.yml
  when: system_hostname is not defined
